FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements_dev.txt .
COPY requirements.txt .

RUN pip install -r requirements_dev.txt

COPY . .

EXPOSE 8080

CMD ["python", "-m", "pytest"]
